### ISSUE TITLE
Fixes required in the spreadsheet of metadata

### ISSUE THREAD

**Issue by sdgamboa** [Bioconductor/BioC2022#25]
@mdozmorov, @Krithika-Bhuvan 

Some notes regarding the metadata spreadsheet: https://docs.google.com/spreadsheets/d/1tGtGffcbCRxQFjE3ej42IcWlN4FJCsuQeZvETt9g0oA/edit#gid=0

+ I noticed  that the field `authors` only include one author and et al in the table of metadata. I think that all authors should be included in this field since we have the information.

+ Sometimes the information is mixed (see [c3e5b3a](https://github.com/Bioconductor/BioC2022/commit/c3e5b3a62218806f898bfda9e2863479170116d0) and lines 27 and 28 in the metadata table). We should fix these in the tables and in the data yaml. And look for other cases.

+ Affiliations are missing for some authors in the table.

**Comment by Krithika-Bhuvan** [comment]
Thanks. Fixed #2 on the excel. Thanks for updating the yaml. For #3, the affiliation is missing in the abstract file. It says "Senior Data Scientist" which is a job role and not affiliation. 
For #1, this is what I was referring to in our Tuesday meeting. Mikhail said to leave it as it is since the current system was working just fine.

**Comment by sdgamboa** [comment]
I think all of these have been fixed. I'm closing this issue.

**Comment by mdozmorov** [comment]
Thanks, Samuel, Krithika!
